version: '3'

services:
  db:
    image: mdillon/postgis:11-alpine
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data/

  app:
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    build: .
    restart: always
    volumes:
      - static_volume:/app/src/static/
      - media_volume_1:/app/src/media/
    depends_on:
      - db

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 1337:80
    depends_on:
      - app
      - swagger
    volumes:
      - static_volume:/app/src/static/
      - media_volume_1:/app/src/media/

  swagger:
    build: ./swagger
    restart: always

volumes:
  db_volume:
  static_volume:
  media_volume_1: