# Generated by Django 2.2.5 on 2019-09-27 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190927_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='color',
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_url', models.FileField(upload_to='')),
                ('video_url', models.FileField(upload_to='')),
                ('user_id', models.CharField(max_length=255)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Match')),
            ],
        ),
    ]
