# Generated by Django 2.2.5 on 2019-09-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190927_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='preview_url',
            new_name='preview',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_url',
            new_name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='start_real_time',
            field=models.DateTimeField(default='2019-09-27T22:02:55Z'),
            preserve_default=False,
        ),
    ]
