# Generated by Django 2.2.5 on 2019-09-28 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190927_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.FileField(upload_to='')),
                ('video', models.FileField(upload_to='')),
                ('fragments', models.ManyToManyField(to='api.Video')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Match')),
            ],
        ),
    ]
