# Generated by Django 2.2.5 on 2019-09-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190928_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='fragments',
            field=models.ManyToManyField(through='api.HighlightFragment', to='api.Video'),
        ),
    ]
