# Generated by Django 2.2.5 on 2019-09-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_highlight_fragments'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_score',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='real_start_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='global_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
