# Generated by Django 2.2.5 on 2019-09-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highlightfragment',
            old_name='second',
            new_name='start_time',
        ),
    ]
