# Generated by Django 2.2.5 on 2019-09-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_video_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='method_score',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='team',
            field=models.CharField(choices=[('HOME', 'HOME'), ('AWAY', 'AWAY')], max_length=20, null=True),
        ),
    ]
