# Generated by Django 2.2.5 on 2019-09-28 19:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190928_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='liked_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
