# Generated by Django 2.2.5 on 2019-09-28 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190928_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.Match'),
        ),
    ]
