# Generated by Django 2.2.5 on 2019-09-29 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190928_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_shift', models.FloatField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Video')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='events',
            field=models.ManyToManyField(through='api.VideoEvent', to='api.Event'),
        ),
    ]
