# Generated by Django 2.2.5 on 2019-09-29 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190929_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_shift', models.FloatField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event')),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Highlight')),
            ],
        ),
    ]
